# Load packages -----------------------------------------------------------

library(DeclareDesign)
library(tidyverse)
library(MASS, exclude = 'select')
library(cmdstanr)
library(posterior)
library(bayesplot)
library(kableExtra)
library(future)
library(furrr)
library(progressr)
library(feather)
library(haven)
library(tools)
library(fs)